GET https://192.168.1.37:5002/api/Customer HTTP/1.1

###

GET https://192.168.1.37:5002/api/Customer/{id} HTTP/1.1

###
POST https://192.168.1.37:5002/api/Customer HTTP/1.1

###
PUT https://192.168.1.37:5002/api/Customer/{id} HTTP/1.1

###
DELETE https://192.168.1.37:5002/api/Customer/{id} HTTP/1.1
content-type: application/json